server {
    listen 8083;
    server_name ekstrom.nu;
    root /usr/share/nginx/html/site3;
    index index.html;

    access_log /var/log/nginx/site3.access.log reqsentry;
    error_log /var/log/nginx/site3.error.log warn;

    location = /old-page { return 301 /new-page; }
    location = /temporary { return 302 /destination; }
    location = /new-page { default_type text/plain; return 200 "ekstrom.nu new page\n"; }
    location = /destination { default_type text/plain; return 200 "ekstrom.nu destination\n"; }
    location = /product { default_type text/plain; return 200 "ekstrom.nu product\n"; }
    location /users/ { return 404; }
    location / { try_files $uri $uri/ =404; }
}
