server {
    listen 8081;
    server_name him.com;
    root /usr/share/nginx/html/site1;
    index index.html;

    access_log /var/log/nginx/site1.access.log reqsentry;
    error_log /var/log/nginx/site1.error.log warn;

    location = /old-page { return 301 /new-page; }
    location = /temporary { return 302 /destination; }
    location = /new-page { default_type text/plain; return 200 "him.com new page\n"; }
    location = /destination { default_type text/plain; return 200 "him.com destination\n"; }
    location = /product { default_type text/plain; return 200 "him.com product\n"; }
    location /users/ { return 404; }
    location / { try_files $uri $uri/ =404; }
}
